"""empty message

Revision ID: ee2497e7e3fe
Revises: 
Create Date: 2020-05-22 19:02:42.841122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2497e7e3fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('home', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('corona', sa.Integer(), nullable=True),
    sa.Column('easter', sa.Integer(), nullable=True),
    sa.Column('view', sa.Integer(), nullable=True),
    sa.Column('feeling', sa.Integer(), nullable=True),
    sa.Column('badfeeling', sa.Integer(), nullable=True),
    sa.Column('alcohol', sa.Integer(), nullable=True),
    sa.Column('eat', sa.Integer(), nullable=True),
    sa.Column('selfimpr', sa.Integer(), nullable=True),
    sa.Column('job', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formdata')
    # ### end Alembic commands ###
